### ISSUE TITLE
Incorrect master name causes endless flood of connection attempts

### ISSUE THREAD

**Issue by tdooner** [flyerhzm/redis-sentinel#53]
In the event that `redis-sentinel` is misconfigured with valid sentinels but an invalid master name, the logic in [discover_slaves](https://github.com/flyerhzm/redis-sentinel/blob/master/lib/redis-sentinel/client.rb#L95) will endlessly loop through all configured sentinels with no timeout.

This has caused us some grief, because it's easy to run out of file descriptors with TIME_WAIT connections to Redis.

I'm happy to work on a PR for this, but wanted to touch base first to see if anyone had preferences on how to address this. I'm leaning toward tracking whether we have connected to every sentinel and waiting for some amount of time after failing on every sentinel (up to `failover_reconnect_timeout` or perhaps a new configurable timout).

Thanks.

**Comment by phuongnd08** [comment]
I've submit a PR here: https://github.com/flyerhzm/redis-sentinel/pull/51

**Comment by flyerhzm** [comment]
@tdooner I have merged the pull request.

**Comment by tdooner** [comment]
Great, thanks for the quick fix @phuongnd08 and @flyerhzm!
