### ISSUE TITLE
Add information that redis-sentinel should not be used with redis >= 3.2

### ISSUE THREAD

**Issue by Draiken** [flyerhzm/redis-sentinel#55]
We've had some problems after upgrading the redis gem while still using the redis-sentinel. It broke the newly added sentinel support on redis-rb 3.2 and didn't raise any errors. We only found out when deploying to production and the redis client was incorrectly attempting to connect to the localhost.

I'd love to see a warning on the readme or something, so this can be avoided by others in the future :)

**Comment by phallstrom** [comment]
:+1:

**Comment by Draiken** [comment]
Yes, just removed the `redis-sentinel` gem, since the `redis` gem now supports it nativelly. Small change to the initial configuration, changing `master_name: lala` to `url: redis://master`.

**Comment by phallstrom** [comment]
Ah.  And if I'd bothered to read more I would have seen this: 

https://github.com/redis/redis-rb#sentinel-support

Definitely worth mentioning in this README/wiki somewhere I agree.
